api_version = "2024-10"
[[extensions]]
name = "t:name"
handle = "product-info-block"
type = "ui_extension"
[[extensions.targeting]]
module = "./src/BlockExtension.tsx"
# The target used here must match the target used in the module file (./src/BlockExtension.jsx)
target = "admin.product-details.block.render"
